{% set name = "mypy-protobuf" %}
{% set version = "1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72ab724299aebd930b88476f6545587bff5bf480697c016097bd188841a56276

build:
  # There is a bat file in there, is it still noarch???
  # noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - protobuf >=3.6

test:
  imports:
    - which protoc-gen-mypy       # [unix]
    - where protoc-gen-mypy.bat   # [win]

about:
  home: https://github.com/dropbox/mypy-protobuf
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: " Generate mypy stub files from protobuf specs"

extra:
  recipe-maintainers:
    - hmaarrfk
